sudo: required
dist: trusty

language: python
python:
  - "2.7"

env:
  - distribution: ubuntu:16.04
#  - distribution: ubuntu:14.04

notifications:
  email: false
  slack:
    rooms:
      secure: UZ8frRZZBOBcg+Ig71A8UUCkqcrpEG7fT93qrTT7R2PssoSSKfPWrvCChbUQl4TbAR6IAO9ZU7iINLBSGagpFPoW45JRQLYKKnbeHogocp/PKVA5yhb7Yu/74WJypORyAHUEB6IpGwuIZvh8+H+FCt35fiifovCEkF47ICvZqokbNkgttn2PqeFVVINLQ4Mit7SDuXFNYdHj3dYpIUg6fbqkrU70K0Pf5aNeHAKjW0S514JesmCq68u0LyG3CH5qPRWLK2GCzMr7i6383rKfXVUHWvOYcK7gzvIHXrwv6RbiObIZoilGBoQ2wES45FGGmpjyLTS1rBpcKRYnHSiq+nDkLWbxozBc9qKBDdArshrQYAcLFzsIt3ck6C5UpjHXHSBvQrqd+VO0c7lLTPF9+XCXh6NNydNdaktHTIKAs90Xq8HUIHk8twtu/3lsrVPJnB8EJoNmGiI3fm3LBw+j5nKDtHNy1MdGhAU4go3nQWSs1P3oZwWVZECE6xusotTrL8g+6Soo8IZe33PO4Yjt7dW3qneJEX0sLBtVrPhnjb5ROQaLyNy7DXW8PSZNb/BiAkG3G2cZ045rD1n98z1YM3//v90YaQNZ/faRK4fi7eGGnAl1Arhz+P5kYZeFPn5Nig3V8/whwMj/Kf83QybU6EeCVDEMG2Yww+uPoaWNUe4=

services:
  - docker

before_install:
  - env | sort
  - docker --version
  - repo=`python scripts/travis/repository_resolver.py`
install:
  - docker pull ${distribution}
  - docker build --cache-from ${distribution} --tag fwk --build-arg repo=${repo} --file scripts/travis/docker/${distribution}/Dockerfile .
  - docker run -dit --name fwk fwk  # Run it detached, with stdin open and TTY to keep it running
  - docker ps -a
script:
  - docker exec -it fwk bash -c "ovs unittest test_alba"
  - docker exec -it fwk bash -c "ovs unittest test_hybrids"
  - docker exec -it fwk bash -c "ovs unittest test_api_configuration"
after_failure:
  - docker logs fwk
