sudo: required
dist: trusty

language: python
python:
  - "2.7"

env:
  - distribution: ubuntu:16.04
#  - distribution: ubuntu:14.04

notifications:
  email: false
  slack:
    rooms:
      secure: Ze8lCMV8b38bfesOMfmAYchAde0c23BMkz4PVc1g1p4sdGBSvrfGx15l8Mp4hfoOme51+wctGa38z42HiESCe0hjM2mEkh2OljxNs39Ug/ZpCBveEi63tt/tIfqBjm16Fvi73Y9LvjTOSKB7isaPaUMgh4QDEZJ0SgN7aIhP/9DOnKVPwX0AcYDO4Bk4Gu9wM9jMoe8wAE1lalZa7iTtTG5L+EtTbok3NhiRKxKRuNOSAtP/8aHsp46lZL64Fix3i6RKXE+DjU5hzXchMwF3Qp0hr63S9G+KnK6H3JRQEsUUdjYQ7nKDMZRI9VQUlncGCjTgz1xLcknhMZ/eAagm82youMkzPgE/HDpfirwWF+G0Vu8DIbKiAuXcfVElhw+d4aoE8HWQkTFxaP057br28NPI2QgPTMDldq3ZakoEgI3PvGyZx4mxYRUWqKKzgl8PQu9cMEfp2x3y+tvEqCxByDvfjZOYn627O1MvxsrLpKEP+6TNRY15q+bKbMXuAJmqD+Ez0KVMbxKVlHot+FXGbEjLQsZqfrD4nQqdweaeMa5Na3NUHXhzOQFk5TrD1PSmjaG7t47qn3T5aDkgBwsbgY8WR2eFkQhGSAHYE96QoSpxibe4eYYf+zXX0gcgHUMWh7T5tW5kvaq/vAcFT99hgsL07UWQ5DGOZCOpIctE2Ik=

services:
  - docker

before_install:
  - env | sort
  - docker --version
  - repo=`python scripts/travis/repository_resolver.py`
install:
  - docker pull ${distribution}
  - docker build --cache-from ${distribution} --tag fwk --build-arg repo=${repo} --file scripts/travis/docker/${distribution}/Dockerfile .
  - docker run -dit --name fwk fwk  # Run it detached, with stdin open and TTY to keep it running
  - docker ps -a
script:
  - docker exec -it fwk bash -c "ovs unittest /opt/OpenvStorage/ovs/dal/tests/test_alba.py"
  - docker exec -it fwk bash -c "ovs unittest /opt/OpenvStorage/ovs/dal/tests/test_hybrids.py"
  - docker exec -it fwk bash -c "ovs unittest /opt/OpenvStorage/ovs/lib/tests/alba_tests/test_lib_alba.py"
  - docker exec -it fwk bash -c "ovs unittest /opt/OpenvStorage/ovs/lib/tests/alba_tests/test_nsmcheckup.py"
  - docker exec -it fwk bash -c "ovs unittest /opt/OpenvStorage/webapps/api/tests/test_api_configuration.py"
after_failure:
  - docker logs fwk
